```yaml
name: Test MyOS

"on":
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test QEMU
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-system-aarch64
          qemu-system-aarch64 --version

      - name: Test MyOS
        run: |
          echo "MyOS workflow fonctionne"
```
