name: Build MyOS Kernel

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

      - name: Télécharger MyOS
        uses: actions/checkout@v4

      - name: Installer les outils
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu binutils-aarch64-linux-gnu

      - name: Compiler le kernel ARM64
        run: |
          aarch64-linux-gnu-gcc \
          -ffreestanding \
          -nostdlib \
          -c kernel/kernel.c \
          -o kernel.o

      - name: Compiler le point d'entrée
        run: |
          aarch64-linux-gnu-as \
          kernel/entry.S \
          -o entry.o

      - name: Vérification
        run: |
          echo "======================"
          echo "      MYOS ARM64"
          echo "======================"
          echo "Kernel compilé"
          echo "Entry compilé"
